### PR TITLE
支持按模板导出到bytes，用于程序内部灵活传递

### PR DESCRIPTION
**Pull request by serfend**

### CODE REVIEW

**Comment by hueifeng** [comment]
This is great. Thanks for the PR. I'll review them :)

**Comment by serfend** [comment]
maybe code format difference exist , for ide default setting

**Comment by xin-lai** [comment]
初看下来没啥问题，晚点我再验证下。
如果可以的话，麻烦补下单元测试。

At first glance there is ok, I will verify it later.
If you can, please write  the unit test.

**Comment by xin-lai** [comment]
Suggest pr to the development branch.

**Pull request closed without merging**
